import { useTheme } from "../context/ThemeContext";

export default function AISummary({ stockData }) {
  const { isDark } = useTheme();

  if (!stockData) {
    return (
      <div className={`flex flex-col items-center justify-center h-full gap-4 ${isDark ? "text-slate-500" : "text-slate-400"}`}>
        <svg className="w-16 h-16 opacity-30" fill="none" viewBox="0 0 24 24" stroke="currentColor" strokeWidth={1}>
          <path d="M9.75 17L9 20l-1 1h8l-1-1-.75-3M3 13h18M5 17H3a2 2 0 01-2-2V5a2 2 0 012-2h14a2 2 0 012 2v10a2 2 0 01-2 2h-2" />
        </svg>
        <p className="text-sm font-medium">Run a prediction to generate an AI summary</p>
      </div>
    );
  }

  const rawSummary = Array.isArray(stockData.summary) ? stockData.summary[0] : stockData.summary;
  const paragraphs = rawSummary ? rawSummary.split("\n").filter((p) => p.trim().length > 0) : [];
  const isBuy = stockData.prediction === "Buy";

  return (
    <div className="flex flex-col gap-5 h-full fade-in-up">
      {/* Header card */}
      <div className={`glass-card p-5 border flex-shrink-0 ${isDark ? "border-blue-500/15" : "border-blue-200"}`}>
        <div className="flex items-center gap-4">
          {/* Gemini icon */}
          <div className={`w-12 h-12 rounded-2xl border flex items-center justify-center flex-shrink-0 ${
            isDark
              ? "bg-gradient-to-br from-blue-500/20 to-violet-500/20 border-blue-500/20 text-blue-400"
              : "bg-blue-50 border-blue-200 text-blue-600"
          }`}>
            <svg className="w-6 h-6" fill="none" viewBox="0 0 24 24" stroke="currentColor" strokeWidth={1.5}>
              <path d="M9.75 17L9 20l-1 1h8l-1-1-.75-3M3 13h18M5 17H3a2 2 0 01-2-2V5a2 2 0 012-2h14a2 2 0 012 2v10a2 2 0 01-2 2h-2" />
            </svg>
          </div>
          <div className="flex-1">
            <div className="flex items-center gap-2">
              <h2 className={`text-sm font-bold ${isDark ? "text-white" : "text-slate-900"}`}>Gemini AI Analysis</h2>
              <span className={`text-[10px] border rounded-full px-2 py-0.5 font-medium ${
                isDark
                  ? "bg-blue-500/15 text-blue-400 border-blue-500/20"
                  : "bg-blue-50 text-blue-700 border-blue-200"
              }`}>
                AI Generated
              </span>
            </div>
            <p className={`text-[11px] mt-1 ${isDark ? "text-slate-400" : "text-slate-500"}`}>
              {stockData.ticker && `Analysis for ${stockData.ticker} · `}
              Generated by Google Gemini 1.5 Flash · Based on ML prediction &amp; technical data
            </p>
          </div>
          {/* Signal badge */}
          {stockData.prediction && (
            <div className={`flex-shrink-0 px-4 py-2 rounded-xl border text-sm font-bold ${
              isBuy
                ? isDark
                  ? "bg-emerald-500/10 border-emerald-500/20 text-emerald-400"
                  : "bg-emerald-50 border-emerald-200 text-emerald-700"
                : isDark
                  ? "bg-rose-500/10 border-rose-500/20 text-rose-400"
                  : "bg-rose-50 border-rose-200 text-rose-700"
            }`}>
              {stockData.prediction}
            </div>
          )}
        </div>
      </div>

      {/* Summary content */}
      <div className="glass-card flex-1 p-5 flex flex-col min-h-0">
        <div className="flex items-center gap-2 mb-4 flex-shrink-0">
          <svg className={`w-4 h-4 ${isDark ? "text-blue-400" : "text-blue-600"}`} fill="none" viewBox="0 0 24 24" stroke="currentColor" strokeWidth={2}>
            <path d="M9 12h6m-6 4h6m2 5H7a2 2 0 01-2-2V5a2 2 0 012-2h5.586a1 1 0 01.707.293l5.414 5.414a1 1 0 01.293.707V19a2 2 0 01-2 2z" />
          </svg>
          <span className={`text-xs font-semibold ${isDark ? "text-slate-300" : "text-slate-800"}`}>Market Analysis Report</span>
        </div>

        {/* Scrollable text */}
        <div className="flex-1 ai-scroll min-h-0 pr-2">
          {paragraphs.length > 0 ? (
            <div className="flex flex-col gap-3">
              {paragraphs.map((para, i) => (
                <p key={i} className={`text-sm leading-relaxed ${isDark ? "text-slate-300" : "text-slate-700"}`}>
                  {para}
                </p>
              ))}
            </div>
          ) : (
            <p className={`text-sm italic ${isDark ? "text-slate-400" : "text-slate-500"}`}>No AI summary available.</p>
          )}
        </div>

        {/* Footer */}
        <div className={`flex-shrink-0 mt-4 pt-4 border-t flex items-center justify-between ${
          isDark ? "border-slate-700/50" : "border-slate-200"
        }`}>
          <p className={`text-[10px] ${isDark ? "text-slate-500" : "text-slate-400"}`}>
            ⚠ AI-generated content is for informational purposes only. Not financial advice.
          </p>
          <div className="flex items-center gap-1.5">
            <div className="w-1.5 h-1.5 rounded-full bg-blue-500"></div>
            <span className={`text-[10px] ${isDark ? "text-slate-500" : "text-slate-400"}`}>Gemini API</span>
          </div>
        </div>
      </div>
    </div>
  );
}