export default function AISummary({ stockData }) {
  if (!stockData) {
    return (
      <div className="flex flex-col items-center justify-center h-full gap-4 text-slate-500">
        <svg className="w-16 h-16 opacity-20" fill="none" viewBox="0 0 24 24" stroke="currentColor" strokeWidth={1}>
          <path d="M9.75 17L9 20l-1 1h8l-1-1-.75-3M3 13h18M5 17H3a2 2 0 01-2-2V5a2 2 0 012-2h14a2 2 0 012 2v10a2 2 0 01-2 2h-2" />
        </svg>
        <p className="text-sm">Run a prediction to generate an AI summary</p>
      </div>
    );
  }

  const rawSummary = Array.isArray(stockData.summary) ? stockData.summary[0] : stockData.summary;
  const paragraphs = rawSummary ? rawSummary.split("\n").filter((p) => p.trim().length > 0) : [];

  return (
    <div className="flex flex-col gap-5 h-full fade-in-up">
      {/* Header card */}
      <div className="glass-card p-5 border border-blue-500/15 flex-shrink-0">
        <div className="flex items-center gap-4">
          {/* Gemini icon */}
          <div className="w-12 h-12 rounded-2xl bg-gradient-to-br from-blue-500/20 to-violet-500/20 border border-blue-500/20 flex items-center justify-center flex-shrink-0">
            <svg className="w-6 h-6 text-blue-400" fill="none" viewBox="0 0 24 24" stroke="currentColor" strokeWidth={1.5}>
              <path d="M9.75 17L9 20l-1 1h8l-1-1-.75-3M3 13h18M5 17H3a2 2 0 01-2-2V5a2 2 0 012-2h14a2 2 0 012 2v10a2 2 0 01-2 2h-2" />
            </svg>
          </div>
          <div className="flex-1">
            <div className="flex items-center gap-2">
              <h2 className="text-sm font-bold text-white">Gemini AI Analysis</h2>
              <span className="text-[10px] bg-blue-500/15 text-blue-400 border border-blue-500/20 rounded-full px-2 py-0.5">
                AI Generated
              </span>
            </div>
            <p className="text-[11px] text-slate-400 mt-1">
              {stockData.ticker && `Analysis for ${stockData.ticker} · `}
              Generated by Google Gemini 3.5 Flash · Based on ML prediction &amp; technical data
            </p>
          </div>
          {/* Signal badge */}
          {stockData.prediction && (
            <div className={`flex-shrink-0 px-4 py-2 rounded-xl border text-sm font-bold ${
              stockData.prediction === "Buy"
                ? "bg-emerald-500/10 border-emerald-500/20 text-emerald-400"
                : "bg-rose-500/10 border-rose-500/20 text-rose-400"
            }`}>
              {stockData.prediction}
            </div>
          )}
        </div>
      </div>

      {/* Summary content */}
      <div className="glass-card flex-1 p-5 flex flex-col min-h-0">
        <div className="flex items-center gap-2 mb-4 flex-shrink-0">
          <svg className="w-4 h-4 text-blue-400" fill="none" viewBox="0 0 24 24" stroke="currentColor" strokeWidth={2}>
            <path d="M9 12h6m-6 4h6m2 5H7a2 2 0 01-2-2V5a2 2 0 012-2h5.586a1 1 0 01.707.293l5.414 5.414a1 1 0 01.293.707V19a2 2 0 01-2 2z" />
          </svg>
          <span className="text-xs font-semibold text-slate-300">Market Analysis Report</span>
        </div>

        {/* Scrollable text */}
        <div className="flex-1 ai-scroll min-h-0 pr-2">
          {paragraphs.length > 0 ? (
            <div className="flex flex-col gap-3">
              {paragraphs.map((para, i) => (
                <p key={i} className="text-sm text-slate-300 leading-relaxed">
                  {para}
                </p>
              ))}
            </div>
          ) : (
            <p className="text-sm text-slate-400 italic">No AI summary available.</p>
          )}
        </div>

        {/* Footer */}
        <div className="flex-shrink-0 mt-4 pt-4 border-t border-slate-700/50 flex items-center justify-between">
          <p className="text-[10px] text-slate-500">
            ⚠ AI-generated content is for informational purposes only. Not financial advice.
          </p>
          <div className="flex items-center gap-1.5">
            <div className="w-1.5 h-1.5 rounded-full bg-blue-400"></div>
            <span className="text-[10px] text-slate-500">Gemini API</span>
          </div>
        </div>
      </div>
    </div>
  );
}